---

- name: Allow haproxy to bind on no local address [VRRP]
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Custom haproxy systemd units
  template:
    src: haproxy.service.j2
    dest: /etc/systemd/system/haproxy.service
    mode: 0644

- name: Allow Stats port when HAProxy Stats and SELinux are enable
  seport:
    ports: "{{ haproxy_stats_port }}"
    proto: tcp
    setype: http_port_t
    state: present
  when: ansible_selinux.status == 'enabled' and haproxy_stats_enabled

- name: Create haproxy main configuration
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    validate: haproxy -f %s -c -q
  notify: Restart haproxy
